language: python
python:
  - "3.6"
  - "3.7"
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: mypy --strict --allow-untyped-calls --ignore-missing-imports ./src/clortho.py && pytest -v
